#!/bin/bash
set -e

# Validate MESH_NODE_NAME to prevent sed injection via special characters.
NODE_NAME="${MESH_NODE_NAME:-ci-runner}"
if [[ "${NODE_NAME}" =~ [^a-zA-Z0-9_-] ]]; then
  echo "ERROR: MESH_NODE_NAME contains invalid characters: ${NODE_NAME}" >&2
  exit 1
fi

git config --global http.https://localhost:7979.sslVerify false

if [ ! -f ~/.mesh/mesh.toml ]; then
  mesh init
  sed -i "s/^name = .*/name = \"${NODE_NAME}\"/" ~/.mesh/mesh.toml
fi

# Always ensure shell mode is enabled and CI env vars are passed through (safe to re-apply on restart).
# BUILDKIT_HOST is passed so pipelines can reach the buildkitd sidecar.
# CONTROL_TOKEN is intentionally excluded — only the watchdog sidecar holds it.
sed -i "s/^execution_modes = .*/execution_modes = [\"shell\"]/" ~/.mesh/mesh.toml
if grep -q '^env_passthrough' ~/.mesh/mesh.toml; then
  sed -i 's/^env_passthrough = .*/env_passthrough = ["REGISTRY_HOST", "GITOPS_REPO_URL", "BUILDKIT_HOST", "BUILDX_BUILDER"]/' ~/.mesh/mesh.toml
else
  sed -i '/^\[runner\]/a env_passthrough = ["REGISTRY_HOST", "GITOPS_REPO_URL", "BUILDKIT_HOST", "BUILDX_BUILDER"]' ~/.mesh/mesh.toml
fi

# Configure docker buildx to use the BuildKit sidecar as the default builder.
# There is no Docker daemon in this pod — we write the buildx config files directly
# so that "docker buildx build" can reach buildkitd without daemon involvement.
# Pipelines use "docker buildx build --push" — no separate "docker push" needed.
BUILDKIT_ENDPOINT="${BUILDKIT_HOST:-tcp://localhost:1234}"
BUILDX_DIR="${HOME}/.docker/buildx"
mkdir -p "${BUILDX_DIR}/instances"

# Wait up to 30s for buildkitd to be ready (TCP connect check).
echo "Waiting for buildkitd at ${BUILDKIT_ENDPOINT}..."
BUILDKITD_READY=0
for i in $(seq 1 30); do
  HOST=$(echo "${BUILDKIT_ENDPOINT}" | sed 's|tcp://||')
  ADDR="${HOST%%:*}"
  PORT="${HOST##*:}"
  if (echo > /dev/tcp/"${ADDR}"/"${PORT}") 2>/dev/null; then
    echo "buildkitd is ready"
    BUILDKITD_READY=1
    break
  fi
  echo "  attempt $i/30 — retrying in 1s"
  sleep 1
done

if [ "${BUILDKITD_READY}" -eq 0 ]; then
  echo "WARNING: buildkitd did not become ready in 30s — proceeding anyway"
fi

# Write the builder config directly (avoids needing a Docker daemon for 'docker buildx create').
# mTLS certs are generated by the gen-buildkit-certs initContainer and mounted at /certs.
cat > "${BUILDX_DIR}/instances/ci-builder" <<EOF
{
  "Name": "ci-builder",
  "Driver": "remote",
  "Nodes": [
    {
      "Name": "ci-builder0",
      "Endpoint": "${BUILDKIT_ENDPOINT}",
      "Platforms": null,
      "DriverOpts": {
        "cacert": "/certs/ca.pem",
        "cert": "/certs/client.pem",
        "key": "/certs/client-key.pem"
      },
      "Flags": []
    }
  ],
  "Dynamic": false
}
EOF
# Set ci-builder as the current builder (same format Docker stores it).
echo "ci-builder" > "${BUILDX_DIR}/current"
echo "buildx ci-builder configured (endpoint: ${BUILDKIT_ENDPOINT})"

exec mesh start
